#!/bin/sh
# SPDX-License-Identifier: MIT OR Apache-2.0
#
# Soft-embed host-collected rtl_nic firmware for linux_dma_soft request_firmware.
#
# Purpose (ABI / module-path lab only):
#   Decompress staged build/linux-drivers/firmware/rtl_nic/*.fw.xz (or plain .fw)
#   into build/linux-drivers/firmware_plain/rtl_nic/, then generate:
#     kernel/proc/rtl_nic_fw_blob.S          — .incbin blobs + end symbols
#     kernel/include/gj/linux_fw_soft_tab.inc — C table rows for soft lookup
#
# Soft ≠ product. Host firmware blobs are often under linux-firmware license
# terms; they are NOT GreenJade product code and are not claimed as G-AC-1.
# No GPL source in tree.
#
# Default set: all rtl8168*.fw (r8169 / 10ec:8168 family). Total uncompressed
# is typically ~30–40 KiB — well under the soft embed cap (~1–2 MiB).
#
# Usage:
#   ./scripts/embed-linux-fw.sh
# Env:
#   GJ_LINUX_DRIVERS   — staging root (default: build/linux-drivers)
#   GJ_LINUX_FW_MAX    — max total uncompressed bytes (default: 2097152 = 2 MiB)
#   GJ_LINUX_FW_GLOB   — basename glob under rtl_nic (default: rtl8168*.fw)
#
# Greppable: embed-linux-fw: PASS | SKIP | FAIL
#
set -eu
root="$(CDPATH= cd -- "$(dirname "$0")/.." && pwd)"
cd "$root"

drv="${GJ_LINUX_DRIVERS:-build/linux-drivers}"
max="${GJ_LINUX_FW_MAX:-2097152}"
glob="${GJ_LINUX_FW_GLOB:-rtl8168*.fw}"
plain="$drv/firmware_plain/rtl_nic"
src_dir="$drv/firmware/rtl_nic"
out_s="kernel/proc/rtl_nic_fw_blob.S"
out_inc="kernel/include/gj/linux_fw_soft_tab.inc"

mkdir -p "$plain" "$(dirname "$out_s")" "$(dirname "$out_inc")"

# Collect candidate basenames from staged xz and/or plain .fw
# shellcheck disable=SC2086
names=""
if [ -d "$src_dir" ]; then
	for f in "$src_dir"/$glob "$src_dir"/${glob}.xz; do
		[ -f "$f" ] || continue
		base=$(basename "$f")
		case "$base" in
		*.fw.xz) base=${base%.xz} ;;
		*.fw) ;;
		*) continue ;;
		esac
		# de-dup
		case " $names " in
		*" $base "*) ;;
		*) names="$names $base" ;;
		esac
	done
fi

# Also accept already-plain firmware_plain inputs
if [ -d "$plain" ]; then
	# shellcheck disable=SC2086
	for f in "$plain"/$glob; do
		[ -f "$f" ] || continue
		base=$(basename "$f")
		case " $names " in
		*" $base "*) ;;
		*) names="$names $base" ;;
		esac
	done
fi

names=$(printf '%s' "$names" | tr ' ' '\n' | sed '/^$/d' | sort -u | tr '\n' ' ')

if [ -z "$(printf '%s' "$names" | tr -d ' \t')" ]; then
	cat >"$out_s" <<'EOF'
/*
 * SPDX-License-Identifier: MIT OR Apache-2.0
 * Copyright (c) 2026 Project GreenJade contributors
 *
 * AUTO-GENERATED by scripts/embed-linux-fw.sh — empty stub (no staged rtl_nic fw).
 * Soft ≠ product. request_firmware remains MISS → -ENOENT until collect+embed.
 */
.section .note.GNU-stack,"",@progbits
EOF
	cat >"$out_inc" <<'EOF'
/* AUTO-GENERATED by scripts/embed-linux-fw.sh — empty table (no staged fw). */
#if defined(LDMAS_FW_DECL)
/* no externs */
#elif defined(LDMAS_FW_TAB)
/* no rows */
#endif
EOF
	echo "embed-linux-fw: SKIP (no $glob under $src_dir or $plain)"
	echo "  tip: ./scripts/collect-linux-drivers.sh  # stages firmware/rtl_nic/*.fw.xz"
	echo "embed-linux-fw: SKIP"
	exit 0
fi

# Materialize plain .fw (decompress xz when needed)
n_ok=0
n_fail=0
total=0
list=""
for base in $names; do
	outf="$plain/$base"
	if [ -f "$src_dir/$base" ]; then
		cp -f "$src_dir/$base" "$outf"
	elif [ -f "$src_dir/${base}.xz" ]; then
		if command -v xzcat >/dev/null 2>&1; then
			xzcat "$src_dir/${base}.xz" >"$outf"
		elif command -v xz >/dev/null 2>&1; then
			xz -dc "$src_dir/${base}.xz" >"$outf"
		else
			echo "embed-linux-fw: FAIL $base (need xzcat/xz to decompress)" >&2
			n_fail=$((n_fail + 1))
			continue
		fi
	elif [ -f "$outf" ]; then
		: # already plain
	else
		echo "embed-linux-fw: SKIP $base (source missing)"
		continue
	fi
	sz=$(wc -c <"$outf" | tr -d ' \t')
	if [ -z "$sz" ] || [ "$sz" -le 0 ]; then
		echo "embed-linux-fw: SKIP $base (empty)"
		rm -f "$outf"
		continue
	fi
	total=$((total + sz))
	list="$list $base"
	n_ok=$((n_ok + 1))
	echo "embed-linux-fw: plain $base ${sz}B"
done

if [ "$n_fail" -gt 0 ]; then
	echo "embed-linux-fw: FAIL decompress errors=$n_fail"
	exit 1
fi

if [ "$n_ok" -eq 0 ]; then
	cat >"$out_s" <<'EOF'
/*
 * SPDX-License-Identifier: MIT OR Apache-2.0
 * Copyright (c) 2026 Project GreenJade contributors
 *
 * AUTO-GENERATED by scripts/embed-linux-fw.sh — empty stub.
 */
.section .note.GNU-stack,"",@progbits
EOF
	cat >"$out_inc" <<'EOF'
/* AUTO-GENERATED by scripts/embed-linux-fw.sh — empty table. */
#if defined(LDMAS_FW_DECL)
#elif defined(LDMAS_FW_TAB)
#endif
EOF
	echo "embed-linux-fw: SKIP (no plain fw materialized)"
	exit 0
fi

if [ "$total" -gt "$max" ]; then
	echo "embed-linux-fw: FAIL total=${total}B max=${max}B (soft embed cap)" >&2
	exit 1
fi

# Emit assembly blobs
{
	cat <<EOF
/*
 * SPDX-License-Identifier: MIT OR Apache-2.0
 * Copyright (c) 2026 Project GreenJade contributors
 *
 * AUTO-GENERATED by scripts/embed-linux-fw.sh — do not hand-edit.
 * Soft-embed host rtl_nic firmware for linux_dma_soft request_firmware HIT.
 * Soft ≠ product. Not G-AC-1. No GPL source.
 * n=${n_ok} total=${total} bytes (gate < ${max})
 */
.section .rodata
EOF
	for base in $list; do
		# C-friendly: rtl8168h-1.fw → rtl8168h_1
		stem=${base%.fw}
		sym=$(printf '%s' "$stem" | tr '-' '_')
		rel="$plain/$base"
		cat <<EOF
.global gj_fw_${sym}_blob
.global gj_fw_${sym}_blob_end
.align 16
gj_fw_${sym}_blob:
    .incbin "$rel"
gj_fw_${sym}_blob_end:

EOF
	done
	cat <<'EOF'
.section .note.GNU-stack,"",@progbits
EOF
} >"$out_s"

# Emit C include used twice by linux_dma_soft.c:
#   #define LDMAS_FW_DECL  → extern blob symbols
#   #define LDMAS_FW_TAB   → table rows { name, data, end }
{
	cat <<EOF
/* AUTO-GENERATED by scripts/embed-linux-fw.sh — do not hand-edit.
 * Soft firmware embed table for linux_dma_soft. Soft≠product.
 * n=${n_ok} total=${total}B
 *
 * Include under LDMAS_FW_DECL (externs) or LDMAS_FW_TAB (rows).
 */
EOF
	echo "#if defined(LDMAS_FW_DECL)"
	for base in $list; do
		stem=${base%.fw}
		sym=$(printf '%s' "$stem" | tr '-' '_')
		cat <<EOF
extern const unsigned char gj_fw_${sym}_blob[];
extern const unsigned char gj_fw_${sym}_blob_end[];
EOF
	done
	echo "#elif defined(LDMAS_FW_TAB)"
	for base in $list; do
		stem=${base%.fw}
		sym=$(printf '%s' "$stem" | tr '-' '_')
		# Linux request_firmware name includes rtl_nic/ prefix
		cat <<EOF
{ "rtl_nic/${base}", gj_fw_${sym}_blob, gj_fw_${sym}_blob_end },
EOF
	done
	echo "#endif /* LDMAS_FW_DECL | LDMAS_FW_TAB */"
} >"$out_inc"

echo "embed-linux-fw: OK n=$n_ok total=${total}B -> $out_s + $out_inc"
echo "  names:$list"
echo "embed-linux-fw: PASS"
exit 0
