#!/bin/sh
# SPDX-License-Identifier: MIT OR Apache-2.0
#
# Generate optional kernel .S embed stubs for staged plain Linux .ko blobs.
#
# Purpose (ABI / module-path development only):
#   Materialize kernel/proc/*_mod_blob.S that .incbin a plain ELF .ko from
#   build/linux-drivers/modules/ — same pattern as init_embed.S / storaged_embed.S.
#   Coordinator wires objects into the kernel link; this script only emits .S.
#
# Honesty:
#   - Host .ko are often GPL. They are NOT GreenJade product code.
#   - Embedding is for lab module-path / size / link smoke — not product AC,
#     not "insmod on GreenJade", not shipping GPL as bar3/T1.
#   - Default size gate: skip if uncompressed .ko >= 512 KiB.
#
# Usage:
#   ./scripts/embed-linux-mod.sh [mod_basename ...]
# Default: r8169
# Optional xHCI (only if plain .ko staged; host often has xhci builtin → SKIP):
#   ./scripts/embed-linux-mod.sh xhci_pci
# Optional USB MSC (often PRESENT when xHCI is builtin — RHEL/el9 class):
#   ./scripts/embed-linux-mod.sh usb-storage
#   ./scripts/embed-linux-mod.sh r8169 usb-storage
#   (usb_storage accepted as alias; file on disk is usually usb-storage.ko)
#
# Env:
#   GJ_LINUX_DRIVERS   — staging root (default: build/linux-drivers)
#   GJ_LINUX_MOD_MAX   — max uncompressed bytes (default: 524288 = 512 KiB)
#   GJ_LINUX_EMBED_OUT — dir for generated .S (default: kernel/proc)
#
# Outputs (when size OK):
#   kernel/proc/r8169_mod_blob.S
#     symbols: gj_r8169_ko_blob / gj_r8169_ko_blob_end
#   kernel/proc/xhci_pci_mod_blob.S  (optional)
#     symbols: gj_xhci_pci_ko_blob / gj_xhci_pci_ko_blob_end
#   kernel/proc/usb_storage_mod_blob.S  (optional; from usb-storage.ko)
#     symbols: gj_usb_storage_ko_blob / gj_usb_storage_ko_blob_end
#   kernel/proc/linux_mod_embed.S  — tiny pattern note (always refresh)
#
# Makefile: r8169_mod_blob.S is always linked; xhci_pci_mod_blob.S and
# usb_storage_mod_blob.S are linked only if the generated .S exists
# (weak symbols in main.c otherwise). Soft≠product.
#
# Greppable: embed-linux-mod: PASS | SKIP | FAIL
#
set -eu
root="$(CDPATH= cd -- "$(dirname "$0")/.." && pwd)"
cd "$root"

drv="${GJ_LINUX_DRIVERS:-build/linux-drivers}"
max="${GJ_LINUX_MOD_MAX:-524288}"
out_dir="${GJ_LINUX_EMBED_OUT:-kernel/proc}"
# shellcheck disable=SC2086
mods="${*:-r8169}"

mkdir -p "$out_dir"

# Pattern template (always small) — documents the embed shape for operators.
cat >"$out_dir/linux_mod_embed.S" <<'EOF'
/*
 * SPDX-License-Identifier: MIT OR Apache-2.0
 * Copyright (c) 2026 Project GreenJade contributors
 *
 * Template / note for Linux .ko blob embeds (module-path lab only).
 * Real embeds are generated by scripts/embed-linux-mod.sh, e.g.:
 *   kernel/proc/r8169_mod_blob.S       →  gj_r8169_ko_blob / _end
 *   kernel/proc/xhci_pci_mod_blob.S    →  gj_xhci_pci_ko_blob / _end (optional;
 *     host xHCI often builtin — no .ko → embed SKIP; main soft path SKIP builtin)
 *   kernel/proc/usb_storage_mod_blob.S →  gj_usb_storage_ko_blob / _end (optional;
 *     host often has usb-storage.ko modular while HC is builtin)
 * Pattern matches init_embed.S / storaged_embed.S (.incbin of a build path).
 *
 * Do not hand-edit product embeds for GPL .ko into the kernel link without
 * an explicit lab target; default kernel build does not require xhci objs.
 */
.section .note.GNU-stack,"",@progbits
EOF

n_ok=0
n_skip=0
n_fail=0
generated=""

emit_one() {
	name="$1"
	# Normalize basename (strip accidental .ko / compression suffixes)
	case "$name" in
	*.ko.xz) name=${name%.ko.xz} ;;
	*.ko.gz) name=${name%.ko.gz} ;;
	*.ko.zst) name=${name%.ko.zst} ;;
	*.ko) name=${name%.ko} ;;
	esac
	# C-friendly symbol fragment: hyphens → underscores
	sym=$(printf '%s' "$name" | tr '-' '_')

	# Hyphen ↔ underscore aliases (modinfo name usb_storage vs file usb-storage.ko)
	name_hy=$(printf '%s' "$name" | tr '_' '-')
	name_us=$(printf '%s' "$name" | tr '-' '_')

	ko=""
	for cand in \
		"$drv/modules/${name}.ko" \
		"$drv/modules_raw/${name}.ko" \
		"$drv/modules/${name_hy}.ko" \
		"$drv/modules_raw/${name_hy}.ko" \
		"$drv/modules/${name_us}.ko" \
		"$drv/modules_raw/${name_us}.ko"
	do
		if [ -f "$cand" ]; then
			ko=$cand
			break
		fi
	done

	if [ -z "$ko" ]; then
		echo "embed-linux-mod: SKIP $name (no plain .ko under $drv/modules or modules_raw)"
		echo "  tip: ./scripts/collect-linux-drivers.sh  # decompresses .ko.xz → .ko"
		n_skip=$((n_skip + 1))
		return 0
	fi
	# Prefer underscore C symbol fragment always (usb-storage → usb_storage)
	sym=$name_us

	# Portable size in bytes
	sz=$(wc -c <"$ko" | tr -d ' \t')
	if [ -z "$sz" ] || [ "$sz" -ge "$max" ]; then
		echo "embed-linux-mod: SKIP $name size=${sz:-?} max=$max (uncompressed >= gate)"
		n_skip=$((n_skip + 1))
		return 0
	fi

	# Prefer path relative to repo root for .incbin (matches other embeds)
	case "$ko" in
	/*)
		# Strip $root/ prefix if under tree
		rel=${ko#"$root"/}
		if [ "$rel" = "$ko" ]; then
			# Outside tree — copy into staging so assemble is reproducible
			mkdir -p "$drv/modules"
			cp -f "$ko" "$drv/modules/${name}.ko"
			rel="$drv/modules/${name}.ko"
		fi
		;;
	*)
		rel=$ko
		;;
	esac

	asm="$out_dir/${sym}_mod_blob.S"
	cat >"$asm" <<EOF
/*
 * SPDX-License-Identifier: MIT OR Apache-2.0
 * Copyright (c) 2026 Project GreenJade contributors
 *
 * AUTO-GENERATED by scripts/embed-linux-mod.sh — do not hand-edit.
 * Embed $rel for module-path lab smoke (host Linux .ko; often GPL).
 * Not product AC. Coordinator wires objs if/when needed.
 * size=${sz} bytes (gate < ${max})
 */
.section .rodata
.global gj_${sym}_ko_blob
.global gj_${sym}_ko_blob_end
.align 16
gj_${sym}_ko_blob:
    .incbin "$rel"
gj_${sym}_ko_blob_end:

.section .note.GNU-stack,"",@progbits
EOF

	echo "embed-linux-mod: OK $name -> $asm (${sz} bytes) symbols=gj_${sym}_ko_blob/_end"
	generated="$generated $asm"
	n_ok=$((n_ok + 1))
}

for m in $mods; do
	[ -n "$m" ] || continue
	emit_one "$m" || n_fail=$((n_fail + 1))
done

echo "embed-linux-mod: done ok=$n_ok skip=$n_skip fail=$n_fail out_dir=$out_dir"
if [ -n "$generated" ]; then
	echo "  generated:$generated"
fi
echo "  template: $out_dir/linux_mod_embed.S"

if [ "$n_fail" -gt 0 ]; then
	echo "embed-linux-mod: FAIL"
	exit 1
fi
if [ "$n_ok" -gt 0 ]; then
	echo "embed-linux-mod: PASS"
else
	echo "embed-linux-mod: SKIP (no embeds emitted)"
fi
exit 0
