#!/bin/sh
# SPDX-License-Identifier: MIT OR Apache-2.0
#
# Enable SSH on the *lab host* for remote hardware-test debug (Grok / operator).
#
# Product freestanding sshd (sshd.elf) is on by default at DUT boot (port 22 /
# net door). This script still enables lab-host OpenSSH for serial/bench access
# while eth-TCP + full crypto KEX on GreenJade is completed.
#
# Workflow:
#   1. DUT boots GreenJade from USB (make hwtest-img / install-hwtest-usb)
#      — product sshd default on; expect serial M0 OK + sshd: live spawn PASS
#   2. Lab host has serial (USB-UART) and/or same LAN
#   3. This script turns on host sshd + installs the hwtest ed25519 pubkey
#      (keys: build/hwtest-keys/id_ed25519 — also packed on GJ-PERSIST/ssh/)
#   4. Operator/Grok: ssh -i build/hwtest-keys/id_ed25519 root@<lab-host>
#   5. On lab host: picocom -b 115200 /dev/ttyUSB0  (GreenJade console)
#   6. Soft-scan a serial capture:
#        ./scripts/gj-product-summary.sh logs/serial-….txt   # soft exit 0
#        ./scripts/gj-quick-keys.sh logs/serial-….txt        # hard product keys
#
# Stick-local alternative (no tree checkout needed on lab host):
#   sudo mount -L GJ-PERSIST /mnt/gj-persist
#   sudo bash /mnt/gj-persist/ssh/enable-lab-ssh.sh
#
# Usage:
#   sudo ./scripts/hwtest-ssh-setup.sh
#   sudo GJ_SSH_USER=myuser ./scripts/hwtest-ssh-setup.sh   # non-root user
set -eu
root="$(CDPATH= cd -- "$(dirname "$0")/.." && pwd)"
cd "$root"
USER_NAME="${GJ_SSH_USER:-root}"

if [ "$(id -u)" -ne 0 ]; then
	echo "run as root: sudo $0" >&2
	exit 1
fi

mkdir -p build/hwtest-keys
if [ ! -f build/hwtest-keys/id_ed25519 ]; then
	if ! command -v ssh-keygen >/dev/null 2>&1; then
		echo "need ssh-keygen" >&2
		exit 1
	fi
	ssh-keygen -t ed25519 -N "" -C "greenjade-hwtest@lab" \
		-f build/hwtest-keys/id_ed25519 >/dev/null
	echo "hwtest-ssh-setup: generated build/hwtest-keys/id_ed25519"
fi
PUB="$(cat build/hwtest-keys/id_ed25519.pub)"
# Soft fingerprint for operator logs (never print private key)
FP="unknown"
if command -v ssh-keygen >/dev/null 2>&1; then
	FP=$(ssh-keygen -lf build/hwtest-keys/id_ed25519.pub 2>/dev/null | awk '{print $2}') || FP="unknown"
fi

if [ "$USER_NAME" = "root" ]; then
	HOME_DIR=/root
else
	HOME_DIR="$(getent passwd "$USER_NAME" | cut -d: -f6)"
	if [ -z "$HOME_DIR" ] || [ ! -d "$HOME_DIR" ]; then
		echo "unknown user: $USER_NAME" >&2
		exit 1
	fi
fi

mkdir -p "$HOME_DIR/.ssh"
chmod 700 "$HOME_DIR/.ssh"
AUTH="$HOME_DIR/.ssh/authorized_keys"
if [ -f "$AUTH" ]; then
	grep -qxF "$PUB" "$AUTH" 2>/dev/null || echo "$PUB" >>"$AUTH"
else
	echo "$PUB" >"$AUTH"
fi
chmod 600 "$AUTH"
chown -R "$USER_NAME:$USER_NAME" "$HOME_DIR/.ssh" 2>/dev/null || true

if [ -d /etc/ssh/sshd_config.d ]; then
	cat >/etc/ssh/sshd_config.d/99-greenjade-hwtest.conf <<EOF
# GreenJade hardware-test remote debug (generated by hwtest-ssh-setup.sh)
PermitRootLogin prohibit-password
PasswordAuthentication no
PubkeyAuthentication yes
ClientAliveInterval 30
EOF
fi

# Start/enable sshd (RHEL/Rocky: sshd; Debian: ssh)
sshd_unit="none"
if command -v systemctl >/dev/null 2>&1; then
	if systemctl list-unit-files 2>/dev/null | grep -q '^sshd\.service'; then
		systemctl enable --now sshd
		systemctl reload sshd || systemctl restart sshd
		sshd_unit="sshd"
	elif systemctl list-unit-files 2>/dev/null | grep -q '^ssh\.service'; then
		systemctl enable --now ssh
		systemctl reload ssh || systemctl restart ssh
		sshd_unit="ssh"
	else
		echo "warn: no sshd/ssh unit found" >&2
	fi
elif command -v service >/dev/null 2>&1; then
	service sshd start 2>/dev/null || service ssh start 2>/dev/null || true
	sshd_unit="service"
fi

# Open firewall port 22 when firewalld is active
if command -v firewall-cmd >/dev/null 2>&1 && firewall-cmd --state >/dev/null 2>&1; then
	firewall-cmd --permanent --add-service=ssh >/dev/null 2>&1 || true
	firewall-cmd --reload >/dev/null 2>&1 || true
fi

# Soft: confirm something is listening on :22
listen_note="listen=:22 unknown"
if command -v ss >/dev/null 2>&1; then
	if ss -ltn 2>/dev/null | grep -qE ':22[[:space:]]'; then
		listen_note="listen=:22 ok"
	else
		listen_note="listen=:22 miss (sshd may still be starting)"
		echo "hwtest-ssh-setup: warn: nothing listening on :22 yet" >&2
	fi
elif command -v netstat >/dev/null 2>&1; then
	if netstat -ltn 2>/dev/null | grep -qE ':22[[:space:]]'; then
		listen_note="listen=:22 ok"
	else
		listen_note="listen=:22 miss"
	fi
fi

IP="$(hostname -I 2>/dev/null | awk '{print $1}')"
HOST="$(hostname -f 2>/dev/null || hostname)"
echo "hwtest-ssh-setup: PASS sshd ready for user=$USER_NAME unit=$sshd_unit $listen_note"
echo "  pubkey fingerprint: $FP"
echo "  from workstation:"
echo "    ssh -i $root/build/hwtest-keys/id_ed25519 ${USER_NAME}@${IP:-$HOST}"
echo "  then on lab host, attach DUT serial:"
echo "    picocom -b 115200 /dev/ttyUSB0"
echo "    # or tee into USB GJ-PERSIST:"
echo "    sudo mount -L GJ-PERSIST /mnt/gj-persist"
echo "    picocom -b 115200 /dev/ttyUSB0 | sudo tee /mnt/gj-persist/logs/serial-\$(date -u +%Y%m%dT%H%MZ).txt"
echo "  Soft-scan capture:"
echo "    ./scripts/gj-product-summary.sh /mnt/gj-persist/logs/serial-….txt"
echo "    ./scripts/gj-quick-keys.sh /mnt/gj-persist/logs/serial-….txt"
echo "  Note: product DUT sshd (sshd.elf :22) is separate from this lab-host OpenSSH"
